### ISSUE TITLE
Help and organization of work

### ISSUE THREAD

**Issue by jader1313** [tombrothers/EntityFrameworkCore.Vfp#1]
@tombrothers How can we assist in the development or testing of the EF Core provider for Visual FoxPro? Do you have any guidance for organizing the work or past experience that we can build on? Do you want this help? Can we communicate through ISSUES?

**Comment by tombrothers** [comment]
This project is in its very early stages so I’m still trying to figure out the work at the moment.  Mainly, I’m just looking at the VfpEntityFrameworkProvider2 unit tests and trying to pull over any relevant tests, one at a time, to get started.  These tests help provide focus for what code needs to be implemented at a minimum. For example, I started with a couple really simple query tests to see that I could wire everything up to perform those queries.  Implementing more complex query tests could be a good place for someone to help with the code.  I’ve just been looking at the EF Core source to understand what needs to be done to get this provider to work.  Additionally, the VfpEntityFrameworkProvider2 code is used to understand the Vfp specific needs for data access and data manipulation.

I’m open to any ideas for this project and communicating though Issues works for me.

**Comment by cvivieca** [comment]
I'm open to colaborate. I will be waiting for issue.

**Comment by Valdas13** [comment]
I wanted to use your EntityFrameworkCore.Vfp project in my solution. But the Build of VS gave a dozen errors related to the Dependencies. I am not very good in C#, but maybe you can give me a little explanation how to use EntityFrameworkCore.Vfp in other solutions?

**Comment by tombrothers** [comment]
@Valdas13 I created a [nuget ](https://www.nuget.org/packages/EntityFrameworkCore.Vfp) package that you can use in your project.

Here is an rough example of how you can use the provider.

```cs
namespace ConsoleApp1 {
    public class Program {
        static void Main(string[] args) {
            using(var context = new NorthwindContext(@"C:\Northwind\Northwind.dbc")) {
                var customers = context.Customers.ToList();
            }
        }
    }

    public class NorthwindContext : DbContext {
        public DbSet<Customer> Customers { get; set; }

        private readonly string _connectionString;

        public NorthwindContext(string connectionString) {
            _connectionString = connectionString;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) =>
            optionsBuilder.UseVfp(_connectionString);
    }

    public class Customer {
        public string CustomerId { get; set; }
        public string CompanyName { get; set; }
    }
}
```

**Comment by tombrothers** [comment]
@cvivieca At the moment, I have two coding items planned.  The first item to is to implement an XmlToCursor rewriter to get the XmlToCursorTests to pass.  The second item is to implement migrations.  You could give one of these a try if you want.  Additionally, I can think of two non-coding items that would be helpful.  The first non-coding issue would be helping me build of a list of issues by testing the provider in a production like scenario (only querying and data manipulation at this point) for the purpose of building up a list of issues.  The second non-coding item would be to start creating a wiki for how to use the provider.

**Comment by Valdas13** [comment]
> @Valdas13 I created a [nuget ](https://www.nuget.org/packages/EntityFrameworkCore.Vfp) package that you can use in your project.
> 
> Here is an rough example of how you can use to provider.
> 
> ```cs
> namespace ConsoleApp1 {
>     public class Program {
>         static void Main(string[] args) {
>             using(var context = new NorthwindContext(@"C:\Northwind\Northwind.dbc")) {
>                 var customers = context.Customers.ToList();
>             }
>         }
>     }
> 
>     public class NorthwindContext : DbContext {
>         public DbSet<Customer> Customers { get; set; }
> 
>         private readonly string _connectionString;
> 
>         public NorthwindContext(string connectionString) {
>             _connectionString = connectionString;
>         }
> 
>         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) =>
>             optionsBuilder.UseVfp(_connectionString);
>     }
> 
>     public class Customer {
>         public string CustomerId { get; set; }
>         public string CompanyName { get; set; }
>     }
> }
> ```

Thank you, it works.

**Comment by Valdas13** [comment]
As I mentioned in a previous comment, I am trying to use EntityFrameworkCore.Vfp in my simple project that works with Pomelo.EntityFrameworkCore.MySql. Using EntityFrameworkCore.Vfp I tried to use the Add-Migration command and got an exception:
`PM> Add-Migration InitialMigration
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.
PM> `
Maybe it's too early to use this feature ?

**Comment by tombrothers** [comment]
@Valdas13 right, it is too early.  I've haven't done any work on migrations yet.
